version: '3'
services:

  nginx:
    build: requirements/NGINX/
    container_name: NGINX
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/dchheang/data:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    build: requirements/WordPress/
    container_name: WordPress
    ports:
      - "9000:9000"
    volumes:
      - "/home/dchheang/data:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    env_file:
      - .env

  mariadb:
    build: requirements/MariaDB/
    container_name: MariaDB
    ports:
      - "3306:3306"
    volumes:
      - /home/dchheang/data:/var/lib/mysql
    networks:
      - backend
    restart: always
    env_file:
      - .env

networks:
  frontend:
  backend:
