version: '3'

services:
  nginx:
    build: requirements/NGINX/
    container_name: NGINX
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    build: requirements/WordPress/
    container_name: WordPress
    ports:
      - "9000:9000"
    volumes:
      - "/home/dchheang/data"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
    restart: always

  mariadb:
    build: requirements/MariaDB/
    container_name: MariaDB
    ports:
      - "3306:3306"
    volumes:
      - "/home/dchheang/data"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME:    ${WP_DATABASE_NAME}
      WP_DATABASE_USR:     ${WP_DATABASE_USR}
      WP_DATABASE_PWD:     ${WP_DATABASE_PWD}
    restart: always

networks:
  frontend:
  backend:
